name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/errornest?sslmode=disable"
      AUTH_SECRET: "ci-auth-secret-test-variable-32-chars-long"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Formatter Check
        run: npx prettier --check .

      - name: Run Linter
        run: npm run lint

      - name: Run Typecheck
        run: npm run typecheck

      - name: Run Unit Tests
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run E2E Tests
        run: npm run test:e2e
